import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@styles/globals.css'
import Script from 'next/script'
import AdminFooter from '@components/AdminFooter'
import AdminTopBar from '@components/AdminTopBar'

import React from 'react'
import AdminMenu from '@/components/AdminMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <link rel="icon" type="image/png" href="assets/images/favicon.png" />
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/assets/css/aos.css" />
        <link rel="stylesheet" href="/assets/css/swiper.min.css" />
        <link rel="stylesheet" href="/assets/css/jquery.fancybox.min.css" />
        <link rel="stylesheet" href="/style.css" />
      </head>
      <body className={inter.className}>
        <AdminTopBar />
        <AdminMenu />
        <section className='container my-5'>{children}</section>
        <AdminFooter />
        <Script src="assets/js/jquery-3.4.0.min.js" strategy='beforeInteractive' />
        <Script src="assets/js/popper.min.js" strategy='lazyOnload' />
        <Script src="assets/js/jquery.easing.min.js" strategy='lazyOnload' />
        <Script src="assets/js/bootstrap.min.js" strategy='lazyOnload' />
        <Script src="assets/js/aos.js" strategy='lazyOnload' />
        <Script src="assets/js/owl.carousel.min.js" strategy='lazyOnload' />
        <Script src="assets/js/swiper.min.js" strategy='lazyOnload' />
        <Script src="assets/js/jquery.fancybox.min.js" strategy='lazyOnload' />
        <Script src="assets/js/jquery.waypoints.min.js" strategy='lazyOnload' />
        <Script src="assets/js/jquery.counterup.min.js" strategy='lazyOnload' />
        <Script src="assets/js/jquery.matchHeight-min.js" strategy='lazyOnload' />
        <Script src="assets/js/bootnavbar.js" strategy='lazyOnload' />
        <Script src="assets/js/main.js" strategy='lazyOnload' />
      </body>
    </html>
  )
}


