import Script from 'next/script'
import React, { useEffect } from 'react'
import Head from 'next/head'
import { Metadata } from 'next'
import SearchModal from '../SearchModal'
import AdminTopBar from '../AdminTopBar'
import AdminMenu from '../AdminMenu'
import AdminFooter from '../AdminFooter'
import { useAuth } from '@/hooks'
import { getCookie } from 'cookies-next'

interface Props {
    children: React.ReactNode,
}
function RootLayout({ children }: Props) {
    const { authLogout } = useAuth()
    const metadata: Metadata = {
        title: 'TRC Admin',
        description: 'Generated by create next app',
    }
    const token = getCookie('token');
    useEffect(() => {
        if (!token || token === 'undefined') {
            authLogout().then((res) => {
                if (res) window.location.href = '/auth'
            })
        }
    }, [token]);

    return (
        <>
            <Head>
                <meta charSet="utf-8" />
                <title>{metadata.title as string}</title>
                <meta name="description" content={metadata.description as string} />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
                <link rel="icon" type="image/png" href="assets/images/favicon.png" />
                <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
                <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
                <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
                <link rel="stylesheet" href="/assets/css/aos.css" />
                <link rel="stylesheet" href="/assets/css/swiper.min.css" />
                <link rel="stylesheet" href="/assets/css/jquery.fancybox.min.css" />
                <link rel="stylesheet" href="/style.css" />
            </Head>
            <header>
                <div>
                    <AdminTopBar />
                    <div className="main-menu-area bg_dark_mobile ">
                        <AdminMenu />
                        <SearchModal />
                    </div>
                </div>
            </header>
            <div className="trc-flex trc-h-[auto] trc-bg-gray-200 trc-mx-[auto] trc-font-sans trc-leading-normal trc-tracking-normal">
                <div className="container trc-my-10">
                    {children}  
                </div>
            </div>
            <AdminFooter />

            <Script src="assets/js/jquery-3.4.0.min.js" strategy='beforeInteractive' />
            <Script src="assets/js/popper.min.js" strategy='lazyOnload' />
            <Script src="assets/js/jquery.easing.min.js" strategy='lazyOnload' />
            <Script src="assets/js/bootstrap.min.js" strategy='lazyOnload' />
            <Script src="assets/js/aos.js" strategy='lazyOnload' />
            <Script src="assets/js/owl.carousel.min.js" strategy='lazyOnload' />
            <Script src="assets/js/swiper.min.js" strategy='lazyOnload' />
            <Script src="assets/js/jquery.fancybox.min.js" strategy='lazyOnload' />
            <Script src="assets/js/jquery.waypoints.min.js" strategy='lazyOnload' />
            <Script src="assets/js/jquery.counterup.min.js" strategy='lazyOnload' />
            <Script src="assets/js/jquery.matchHeight-min.js" strategy='lazyOnload' />
            <Script src="assets/js/bootnavbar.js" strategy='lazyOnload' />
            <Script src="assets/js/main.js" strategy='lazyOnload' />
        </>
    )
}

export default RootLayout
